### ISSUE TITLE
Could you make a maverick theme as Casper ?

### ISSUE THREAD

**Issue by ghost** [Reedo0910/Maverick-Theme-Prism#1]
Could you make a maverick theme as Casper  V2.X ?
https://github.com/TryGhost/Casper/releases/tag/2.11.2

**Comment by Reedo0910** [comment]
Hi, xiyizhou. For now, I would say No.
And since the current Maverick does not officially support `post cover` property, I may find it difficult to make something like Casper on Maverick.
Thx.

**Comment by ghost** [comment]
thanks for reply ！have a good day
